version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/insurance
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: "Nac@020/16"
    depends_on:
      - mysql

  mysql:
    image: public.ecr.aws/docker/library/mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: insurance
      MYSQL_USER: developer
      MYSQL_PASSWORD: "Nac@020/16"
      MYSQL_ROOT_PASSWORD: "Ny098$$251"
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
