spring:
  application:
    name: ClaimsManagement

  datasource:
    url: jdbc:mysql://localhost:3306/claims
    username: developer
    password: Nac@020/16

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
    properties:
      max.request.size: 10485760

server:
  port: 8080
