spring:
  application:
    name: InsuranceManagement

  datasource:
    url: jdbc:mysql://mysql:3306/insurance
    username: developer
    password: Nac@020/16
    hikari:
     connection-timeout: 30000
     maximum-pool-size: 5
     initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      acks: all
#      retries: 3
#      batch-size: 16384
#      linger-ms: 1
#      buffer-memory: 33554432
#    properties:
#      max.request.size: 10485760



#    consumer:
#          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#          properties:
#            spring:
#              json:
#                trusted:
#                  packages: com.common.dto
#            reconnect.backoff.ms: 1000
#            retry.backoff.ms: 1000

server:
  port: 8080
